### ISSUE TITLE
Station cargo renders over the top of vehicles

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1483]
**Version information:**
 - Platform: Win 11
 - Version: e.g. master
 - Build/commit: master

**Describe the bug**
Station cargo renders over the top of vehicles

**To Reproduce**
Look at any train in a station with cargo

**Expected behaviour**
Cargo renders behind vehicle ins tation

**Screenshots**
![image](https://user-images.githubusercontent.com/7483209/165073797-cd6114e5-691f-4e17-ad57-33386de00f1b.png)
![image](https://user-images.githubusercontent.com/7483209/165073830-ed7bb1f7-c540-4b25-9662-a6ea2e53a929.png)

**Additional context**
Probably caused by either #1390 or #1432

**Comment by duncanspumpkin** [comment]
I think this issue is corrected now.

**Comment by AaronVanGeffen** [comment]
Looks like this is still happening. We recently received other reports of the same issue (#1601, #1717)

**Comment by AaronVanGeffen** [comment]
I can't reproduce the bug vehicles and cargo overlapping. However, there is an issue with cargo overlapping with the station pillars that exists in both vanilla (!) and early versions of OpenLoco. I've attempted to fix that in #2245.

@LeftofZen Could you confirm cargo and vehicles no longer overlap?

**Comment by LeftofZen** [comment]
The station is overdrawing the cargo sprite
![Image](https://github.com/user-attachments/assets/f0c1278c-41c9-4c6c-98c5-a7d0134d16ed)

The cargo/station sprite ordering issue (image 5) starts in 22.05, issue not present in 22.04. I assume it was from https://github.com/OpenLoco/OpenLoco/pull/1432
